//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Ogrenci_Kayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int OgrID { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrMail { get; set; }
        public string OgrFotograf { get; set; }
        public string OgrAdres { get; set; }
    }
}
